// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiQXRWM3Jnxin_-nXAlal5CL8mfHnEeKk',
    appId: '1:1065207278302:web:5666d4d58696dece85b04f',
    messagingSenderId: '1065207278302',
    projectId: 'ta9sela',
    authDomain: 'ta9sela.firebaseapp.com',
    storageBucket: 'ta9sela.firebasestorage.app',
    measurementId: 'G-6QHM59008S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqw_JI9Go1HkGBHk80IY8g2jbeTn3WaYU',
    appId: '1:1065207278302:android:8d0e6b8f5c423e4385b04f',
    messagingSenderId: '1065207278302',
    projectId: 'ta9sela',
    storageBucket: 'ta9sela.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6pptbAK_NMrFby03Onp3u1sufB9w5c28',
    appId: '1:1065207278302:ios:fb5651ea5bca705385b04f',
    messagingSenderId: '1065207278302',
    projectId: 'ta9sela',
    storageBucket: 'ta9sela.firebasestorage.app',
    iosBundleId: 'com.example.ta9selaNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6pptbAK_NMrFby03Onp3u1sufB9w5c28',
    appId: '1:1065207278302:ios:fb5651ea5bca705385b04f',
    messagingSenderId: '1065207278302',
    projectId: 'ta9sela',
    storageBucket: 'ta9sela.firebasestorage.app',
    iosBundleId: 'com.example.ta9selaNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiQXRWM3Jnxin_-nXAlal5CL8mfHnEeKk',
    appId: '1:1065207278302:web:b58603e5f538dbef85b04f',
    messagingSenderId: '1065207278302',
    projectId: 'ta9sela',
    authDomain: 'ta9sela.firebaseapp.com',
    storageBucket: 'ta9sela.firebasestorage.app',
    measurementId: 'G-5QQW1W5Y2L',
  );
}
